#!/usr/bin/env bash
# Configure Nginx to add X-Served-By header

apt-get update -y
apt-get install -y nginx

sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
