#!/usr/bin/env bash
# Install and configure HAProxy to load balance web-01 and web-02

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy backend
sed -i '/^backend /,/^$/d' /etc/haproxy/haproxy.cfg

cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 44.211.163.139:80 check
    server web-02 54.152.42.164:80 check
EOF

service haproxy restart
