#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend Lorris_frontend
    bind *:80
    default_backend lorris_backend

backend lorris_backend
    balance roundrobin
    server 7021-web-01 	44.211.163.139 check
    server 7021-web-02 	54.152.42.164 check
EOF

sudo service haproxy restart